{
 "title": "BAI -PJ.03-Suphanburi (0164)",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><p style=\"background-color:#009ACD; color:#fff; font-weight: bold;\">\n<font size=\"6\"> DASHBOARD </font></p> </center>"
   }
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"btg/supan\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"t_supan_1\" or r[\"_measurement\"] == \"t_supan_2\" or r[\"_measurement\"] == \"t_supan_3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> map(fn: (r) => ({\r\n      r with _measurement: \r\n        if r[\"_measurement\"] == \"t_supan_1\" then \"Temp 1\" else \r\n        if r[\"_measurement\"] == \"t_supan_2\" then \"Temp 2\" else \r\n        if r[\"_measurement\"] == \"t_supan_3\" then \"Temp 3\" else r[\"_measurement\"]\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"btg/supan\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"h_supan_1\" or r[\"_measurement\"] == \"h_supan_2\" or r[\"_measurement\"] == \"h_supan_3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> map(fn: (r) => ({\r\n      r with _measurement: \r\n        if r[\"_measurement\"] == \"h_supan_1\" then \"Humidity 1\" else \r\n        if r[\"_measurement\"] == \"h_supan_2\" then \"Humidity 2\" else \r\n        if r[\"_measurement\"] == \"h_supan_3\" then \"Humidity 3\" else r[\"_measurement\"]\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"btg/supan\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"t_supan_1\" or r[\"_measurement\"] == \"t_supan_2\" or r[\"_measurement\"] == \"t_supan_3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> map(fn: (r) => ({\r\n      r with _measurement: \r\n        if r[\"_measurement\"] == \"t_supan_1\" then \"Temp 1\" else \r\n        if r[\"_measurement\"] == \"t_supan_2\" then \"Temp 2\" else \r\n        if r[\"_measurement\"] == \"t_supan_3\" then \"Temp 3\" else r[\"_measurement\"]\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"btg/supan\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"h_supan_1\" or r[\"_measurement\"] == \"h_supan_2\" or r[\"_measurement\"] == \"h_supan_3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> map(fn: (r) => ({\r\n      r with _measurement: \r\n        if r[\"_measurement\"] == \"h_supan_1\" then \"Humidity 1\" else \r\n        if r[\"_measurement\"] == \"h_supan_2\" then \"Humidity 2\" else \r\n        if r[\"_measurement\"] == \"h_supan_3\" then \"Humidity 3\" else r[\"_measurement\"]\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"btg/supan\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vol_supan_1\" or r[\"_measurement\"] == \"vol_supan_2\" or r[\"_measurement\"] == \"vol_supan_3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> map(fn: (r) => ({\r\n      r with _measurement: \r\n        if r[\"_measurement\"] == \"vol_supan_1\" then \"Voltage 1\" else \r\n        if r[\"_measurement\"] == \"vol_supan_2\" then \"Voltage 2\" else \r\n        if r[\"_measurement\"] == \"vol_supan_3\" then \"Voltage 3\" else r[\"_measurement\"]\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 23 },
   "targets": [
    {
     "alias": "curent1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cur_supan_1",
     "query": "from(bucket: \"btg/supan\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cur_supan_1\" or r[\"_measurement\"] == \"cur_supan_2\" or r[\"_measurement\"] == \"cur_supan_3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> map(fn: (r) => ({\r\n      r with _measurement: \r\n        if r[\"_measurement\"] == \"cur_supan_1\" then \"Current 1\" else \r\n        if r[\"_measurement\"] == \"cur_supan_2\" then \"Current 2\" else \r\n        if r[\"_measurement\"] == \"cur_supan_3\" then \"Current 3\" else r[\"_measurement\"]\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "curent2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cur_supan_2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "curent3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cur_supan_3",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "alias": "power1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pow_supan_1",
     "query": "from(bucket: \"btg/supan\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pow_supan_1\" or r[\"_measurement\"] == \"pow_supan_2\" or r[\"_measurement\"] == \"pow_supan_3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> map(fn: (r) => ({\r\n      r with _measurement: \r\n        if r[\"_measurement\"] == \"pow_supan_1\" then \"Power 1\" else \r\n        if r[\"_measurement\"] == \"pow_supan_2\" then \"Power 2\" else \r\n        if r[\"_measurement\"] == \"pow_supan_3\" then \"Power 3\" else r[\"_measurement\"]\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "power2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pow_supan_2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "power3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pow_supan_3",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 33 },
   "options": {
    "content": "<center><p style=\"background-color:#009ACD; color:#fff; font-weight: bold;\">\n<font size=\"6\"> POWER USAGE PANEL </font></p></center>"
   }
  },
  {
   "title": "Average Power Usage",
   "type": "gauge",
   "gridPos": { "h": 24, "w": 4, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"btg/supan\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pow_supan_1\" or r[\"_measurement\"] == \"pow_supan_2\" or r[\"_measurement\"] == \"pow_supan_3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> map(fn: (r) => ({\r\n      r with _measurement: \r\n        if r[\"_measurement\"] == \"pow_supan_1\" then \"Power 1\" else \r\n        if r[\"_measurement\"] == \"pow_supan_2\" then \"Power 2\" else \r\n        if r[\"_measurement\"] == \"pow_supan_3\" then \"Power 3\" else r[\"_measurement\"]\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "Daily Power Cost",
   "type": "stat",
   "gridPos": { "h": 24, "w": 4, "x": 4, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Baht" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"btg/supan\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pow_supan_1\" or r[\"_measurement\"] == \"pow_supan_2\" or r[\"_measurement\"] == \"pow_supan_3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\r\n      r with _value: (float(v: r._value) / 1000.0) * 24.0 * 4.0\r\n  }))\r\n  |> yield(name: \"calculated\")\r\n"
    }
   ]
  },
  {
   "title": "Electricity Bills / month",
   "type": "stat",
   "gridPos": { "h": 24, "w": 4, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Baht" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Vaccine Storage 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pow_supan_1",
     "query": "SELECT (mean(\"value\")  / 1000)*30*24*4 FROM \"pow_supan_1\" WHERE $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000*30*24*4" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Vaccine Storage 2",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cur_supan_2",
     "query": "SELECT (mean(\"value\")  / 1000)*30*24*4 FROM \"pow_supan_2\" WHERE $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000*30*24*4" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Vaccine Storage 3",
     "query": "SELECT (mean(\"value\")  / 1000)*30*24*4 FROM \"pow_supan_3\" WHERE $timeFilter GROUP BY time(1d) fill(null)"
    }
   ]
  },
  {
   "title": "Average Power Usage R1/ Day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Vaccine Storage 1(R1)",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pow_supan_1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Power Usage R2/ Day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Vaccine Storage 2(R2)",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pow_supan_2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Power Usage R3/ Day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Vaccine Storage 3(R2)",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pow_supan_3",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 59 },
   "options": {
    "content": "<center><p style=\"background-color:#ad0317; color:#fff; font-weight: bold;\">\n<font size=\"6\"> ALARM PANEL </font></p> </center>"
   }
  },
  {
   "title": "Alarm status ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "supan_alarm_status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alarm status",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 61 },
   "targets": [
    {
     "alias": "Alarm State",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "supan_alarm_status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}